name: test_env
channels:
  - conda-forge  
dependencies:
  - python=3.5
  - dask
  - distributed
  - bottleneck
  - netCDF4
  - xarray>=0.11.3
  - cartopy
  - esmpy
  - intake-xarray
  - ffmpeg
  - geopy
  - xesmf
  - xgcm>=0.2.0
  - Ipython
  - tqdm
  - pytest
  - pytest-cov
  - pytest-env
  - codecov
  - flake8
  - pip:
    - git+https://github.com/xgcm/xmitgcm.git
