name: test_env
channels:
  - conda-forge  
dependencies:
  - python=3.5
  - dask
  - distributed
  - bottleneck
  - netCDF4
  - xarray>=0.11.3
  - cartopy
  - esmpy
  - intake-xarray
  - ffmpeg
  - pytest
  - pytest-cov
  - pytest-env
  - codecov
  - pip:
    - geopy
    - xgcm>=0.2.0
    - xesmf
    - xgcm
    - git+https://github.com/xgcm/xmitgcm.git
