name: test_env
channels:
  - conda-forge  
dependencies:
  - python=3.5
  - dask
  - distributed
  - bottleneck
  - netCDF4
  - xarray
  - cartopy
  - esmpy
  - geoviews
  - pytest
  - pip:
    - pyviz
    - hvplot
    - xgcm
    - xesmf
    - codecov
    - pytest-cov
